insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (1, 'New York', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (2, 'Los Angeles', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (3, 'Chicago', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (4, 'Houston', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (5, 'Phoenix', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (6, 'Philadelphia', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (7, 'San Antonio', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (8, 'San Diego', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (9, 'Dallas', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (10, 'San Jose', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (11, 'Austin', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (12, 'Jacksonville', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (13, 'Fort Worth', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (14, 'Columbus', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (15, 'San Francisco', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (16, 'Charlotte', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (17, 'Indianapolis', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (18, 'Seattle', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (19, 'Denver', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (20, 'Washington', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (21, 'Boston', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (22, 'El Paso', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (23, 'Nashville', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (24, 'Detroit', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (25, 'Oklahoma City', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (26, 'Portland', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (27, 'Las Vegas', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (28, 'Memphis', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (29, 'Louisville', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (30, 'Baltimore', true, current_timestamp, 0, null, null);
insert into "CityEntity" ("Id", "Name", "IsActive", "CreatedAt", "CreatedBy", "UpdatedAt", "UpdatedBy") values (31, 'Milwaukee', true, current_timestamp, 0, null, null);