name: Pack and publish nuget packages
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  pack-and-publish-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
        
      - name: Pack Contracts
        run: dotnet pack src/LSCore.Contracts/LSCore.Contracts.csproj -c Release
        
      - name: Publish Contracts
        run: dotnet nuget push src/LSCore.Contracts/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  pack-and-publish-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
        
      - name: Pack Domain
        run: dotnet pack src/LSCore.Domain/LSCore.Domain.csproj -c Release
        
      - name: Publish Domain
        run: dotnet nuget push src/LSCore.Domain/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  pack-and-publish-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
        
      - name: Pack Repository
        run: dotnet pack src/LSCore.Repository/LSCore.Repository.csproj -c Release
        
      - name: Publish Repository
        run: dotnet nuget push src/LSCore.Repository/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
  
  pack-and-publish-framework:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
        
      - name: Pack Framework
        run: dotnet pack src/LSCore.Framework/LSCore.Framework.csproj -c Release

      - name: Publish Framework
        run: dotnet nuget push src/LSCore.Framework/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
  
  pack-and-publish-dependency-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack DependencyInjection
        run: dotnet pack src/LSCore.DependencyInjection/LSCore.DependencyInjection.csproj -c Release

      - name: Publish DependencyInjection
        run: dotnet nuget push src/LSCore.DependencyInjection/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
  
  pack-and-publish-api-client-rest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack DependencyInjection
        run: dotnet pack src/LSCore.ApiClient.Rest/LSCore.ApiClient.Rest.csproj -c Release

      - name: Publish DependencyInjection
        run: dotnet nuget push src/LSCore.ApiClient.Rest/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
  pack-and-publish-api-client-rest-di:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Pack DependencyInjection
        run: dotnet pack src/LSCore.ApiClient.Rest.DependencyInjection/LSCore.ApiClient.Rest.DependencyInjection.csproj -c Release

      - name: Publish DependencyInjection
        run: dotnet nuget push src/LSCore.ApiClient.Rest.DependencyInjection/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate